<?php defined('SYSPATH') or die('No direct script access.');

// Read more: http://wiki.answers.com/Q/What_are_some_adjectives_that_begin_with_the_letter_E#ixzz1et9La9m5
// Read more: http://wiki.answers.com/Q/What_animals_start_with_the_letter_e#ixzz1et9dehlQ

return array(
	'adjectives' => array(
		'eager',
		'early',
		'earnest',
		'earsplitting',
		'earthly',
		'earthy',
		'easy',
		'easy-going',
		'eatable',
		'eaten',
		'ebbing',
		'ebony',
		'eccentric',
		'ecclesiastic',
		'ecclesiastical',
		'echoey',
		'eclectic',
		'economic',
		'economical',
		'ecstatic',
		'edgy',
		'edible',
		'edited',
		'educated',
		'eerie',
		'effective',
		'effervescent',
		'efficacious',
		'efficient',
		'effluent',
	),
	'animals' => array(
		'Eagle',
		'Earthworm',
		'Earwig',
		'Eastern glass lizard',
		'Eastern newt',
		'Echidna',
		'Eel',
		'Eeve',
		'Eft',
		'Egret',
		'Eider',
		'Eidolon helvum',
		'Ekaltadeta',
		'Eland',
		'Electric Eel',
		'Elephant',
		'Elephant seal',
		'Elephant beetle',
		'Elk',
		'Elver',
		'Emerald tree skink',
		'Emperor penguin',
		'Emperor shrimp',
		'Emu',
		'English Pointer',
		'English Setter',
		'Equestrian',
		'Ermine',
		'Erne',
		'Eskimo dog',
		'Esok',
		'Estuarine crocodile',
		'Ethiopian wolf',
		'European fire salamander',
		'Ewe',
		'Eyas',
		'Eyra',
	)
);