<?php defined('SYSPATH') or die('No direct script access.');

// Read more: http://wiki.answers.com/Q/What_are_some_adjectives_that_begin_with_the_letter_E#ixzz1et9La9m5
// Read more: http://wiki.answers.com/Q/What_animals_start_with_the_letter_e#ixzz1et9dehlQ

return array(
	'adjectives' => array(
		'Fabled',
		'fabulous',
		'factual',
		'fad',
		'faded',
		'failed',
		'failing',
		'fair',
		'faithful',
		'faithless',
		'fake',
		'fallacious',
		'fallow',
		'false',
		'faltering',
		'famished',
		'famous',
		'fanatical',
		'fanciful',
		'fancy',
		'fantabulous',
		'fantastic',
		'fantastical',
		'Far',
		'fascinated',
		'fascinating',
		'fashionable',
		'fast',
		'fastidious',
		'fasting',
		'fat',
		'fatal',
		'fated',
		'fatigued',
		'fatty',
		'faulty',
		'favorable',
		'Feared',
		'fearful',
		'fearsome',
		'fearing',
		'fearless',
		'feathered',
		'feeble',
		'feigned',
		'feisty',
		'feline',
		'feminine',
		'feral',
		'ferocious',
		'fertile',
		'fervent',
		'festering',
		'festive',
		'festooned',
		'fey',
		'fickle',
		'fictional',
		'fictitious',
		'fidgety',
		'Fierce',
		'fiery',
		'Filipino',
		'filled',
		'filthy',
		'final',
		'financial',
		'fine',
		'finicky',
		'finished',
		'Finnish',
		'firm',
		'first',
		'fishy',
		'fit',
		'fitted',
		'fitful',
		'five',
		'fixated',
		'free',
		'fizzy',
		'flabby',
		'flagrant',
		'flaky',
		'flamboyant',
		'flammable',
		'flared',
		'flashy',
		'flat',
		'flattering',
		'flatulent',
		'flawless',
		'flecked',
		'flexible',
		'flighty',
		'flippant',
		'flirtatious',
		'flirty',
		'flitting',
		'floppy',
		'floury',
		'flowery',
		'fluctuating',
		'Fluent',
		'fluid',
		'fluky',
		'flustered',
		'fluted',
		'flying',
		'foamy',
		'focused',
		'folksy',
		'foolish',
		'forceful',
		'foregoing',
		'foreign',
		'forgetful',
		'forked',
		'formal',
		'formidable',
		'fortunate',
		'forward',
		'foul',
		'fouled',
		'found',
		'four',
		'foxy',
		'fractured',
		'fragile',
		'fragmented',
		'fragrant',
		'frail',
		'frank',
		'frankly',
		'frantic',
		'fraudulent',
		'freaky',
		'free',
		'French',
		'frenetic',
		'fresh',
		'fretful',
		'friendly',
		'frightening',
		'Frightened',
		'frightful',
		'Frigid',
		'frilly',
		'frisky',
		'frivolous',
		'frizzy',
		'frosted',
		'frosty',
		'frothy',
		'frozen',
		'frugal',
		'frumpy',
		'frustrating',
		'fudgy',
		'full',
		'full-figured',
		'fun',
		'functional',
		'funky',
		'funny',
		'furrowed',
		'furry',
		'furtive',
		'fussy',
		'futile',
		'futuristic',
		'fuzzy',
	),
	'animals' => array(
		'Fairy Bluebird',
		'Fairy Fly',
		'falcon',
		'Fallow deer',
		'Fantail',
		'Fan worms',
		'Fat-tailed dunnart',
		'Fawn',
		'Felid',
		'Felidae',
		'Feline',
		'Fennec Fox',
		'Ferret',
		'Fiddler crab',
		'Field mouse',
		'Finch',
		'Finnish spitz',
		'Fin whale',
		'Fire bellied toad',
		'Firecrest',
		'Firefly',
		'Fish',
		'Flamingo',
		'Flatfish',
		'Flea',
		'Flicker',
		'Flickertail squirrel',
		'Flies',
		'Flounder',
		'Fluke',
		'Fly',
		'Flycatcher',
		'flying fish',
		'Flying Fox',
		'Flying lemur',
		'Flying squirrel',
		'Foal',
		'Fossa',
		'Fowl',
		'Fox',
		'Foxhound',
		'Fox terrier',
		'Freshwater eel',
		'Frigate bird',
		'Frilled lizard',
		'Frog',
		'Frogmouth',
		'Fruit bat',
		'Fugu',
		'Fulmar',
		'Funnel weaver spider',
		'Fur seal',
	)
);