<?php defined('SYSPATH') or die('No direct script access.');

// Read more: http://wiki.answers.com/Q/What_are_some_adjectives_that_begin_with_the_letter_E#ixzz1et9La9m5
// Read more: http://wiki.answers.com/Q/What_animals_start_with_the_letter_e#ixzz1et9dehlQ

return array(
	'adjectives' => array(
		'gallant',
		'giant',
		'gross',
		'grumpy',
		'grouchy',
		'glorious',
		'gargantuan',
		'guarded',
		'glad',
		'gilded',
		'guarded',
		'grateful',
		'gentle',
		'genuine',
		'gushing',
		'gurgling',
		'gasping',
		'great',
		'grand',
		'grandiose',
		'garbled',
		'girlie',
		'Girlish',
		'Glisten',
		'Gleam',
		'Glaring',
		'gigantic',
		'Goofy',
		'green',
		'Grey',
		'Ghoulish',
		'Grainy',
		'Greek',
		'Grueling',
		'Glittery',
		'Gleeful',
		'Gloating',
		'Glowing',
		'Gaunt',
		'Gruesome',
		'Godly',
		'Godlike',
		'Gusty',
		'Gushy',
		'Gracious',
		'Golden',
		'gregarious',
		'gabby',
		'garrulous',
		'godly',
		'greedy',
		'generous',
		'ghastly',
		'ghostly',
		'goodhearted',
		'good-humored',
		'good-natured',
		'grisly',
		'gritty',
		'Gonadic',
		'grade',
		'grubbing',
		'guard',
		'granter',
		'grumbler',
		'gentle',
		'gifted',
		'glowing',
		'glamorize',
		'glittering',
		'gourmet',
		'Gothic',
		'Goethe',
		'geothermal',
		'gaudy',
		'gawky',
		'gay',
		'graceful',
		'good',
		'grouchy',
		'grimy',
		'giant',
		'gross',
		'grumpy',
		'grouchy',
		'glorious',
		'gentle',
		'genuine'
	),
	'animals' => array(
		'Galapagos Turtle',
		'Garter Snake',
		'Gazelle',
		'Gecko',
		'Gerbil',
		'German shepherd dog',
		'Giant Panda',
		'Giant Salamander',
		'Giant Squid',
		'Gibbon',
		'Gila Monster',
		'Giraffe',
		'gnat',
		'Gnu',
		'goat',
		'goldfish',
		'Goose',
		'Gopher',
		'Gorilla',
		'grasshopper',
		'Grass Snake',
		'Great Ape',
		'Great White Shark',
		'Green Trutle',
		'Grizzly Bear',
		'Ground Hog',
		'Grunion',
		'Guinea Fowl',
		'Guinea Pig',
		'Gull',
		'Guppy',
		'Gypsy Moth'
	)
);