<?php defined('SYSPATH') or die('No direct script access.');

// Read more: http://wiki.answers.com/Q/What_are_some_adjectives_that_begin_with_the_letter_E#ixzz1et9La9m5
// Read more: http://wiki.answers.com/Q/What_animals_start_with_the_letter_e#ixzz1et9dehlQ

return array(
    'adjectives' => array(
        'interesting',
        'intelligent',
        'informative',
        'ignorant',
        'indecipherable',
        'invincible',
        'indeterminable',
        'instrumental',
        'inconsistent',
        'inconsiderate',
        'impermeable',
        'impervious',
        'impressive',
        'insubordinate',
        'impatient',
        'inactive',
        'inane',
        'innate',
        'inapplicable',
        'inauthentic',
        'inbred',
        'incalculable',
        'incandescent',
        'incapacitated',
        'insectivorous',
        'incidental',
        'incipient',
        'implicit',
        'incognito',
        'incoherent',
        'impossible',
        'incombustible',
        'inconvenient',
        'incompetent',
        'inconceivable',
        'inconclusive',
        'incontinent',
        'inconsequential',
        'incredulous',
        'incriminating',
        'incomplete',
        'immortal',
        'Immature',
        'incredible',
        'impatient',
        'important',
        'icky',
        'incomprehensible',
        'ignorant',
        'icy',
        'Inspirational',
        'Indescribable',
        'Intangible',
        'Independent',
        'Influential',
        'Imperfect',
        'Indented',
        'Invisible',
        'inconsiderate',
        'insincere',
        'ignorant',
        'impulsive',
        'insane',
        'inane',
        'irrational',
        'irradiating',
        'idiotic',
        'immaculate',
        'illiterate',
        'impressive',
        'intense',
        'irresistible',
        'indestructible',
        'irreverent',
        'ineluctable',
        'Impossible',
        'Incorrect',
        'Incompetent',
        'Ill',
        'Irritating',
        'Icy',
        'International',
        'Inorganic',
        'Interesting',
        'Intelligent',
        'Immense',
        'Informative',
        'Invincible',
        'Ignorant',
        'Impressive',
        'impish',
        'inner',
        'indigo',
        'individual',
        'ill',
        'impersonal',
        'idyllic',
        'impartial',
        'illogical',
        'idiosyncratic',
        'illustrious',
        'illuminating',
    ),
    'animals' => array(
        'Ibis',
        'Ibex',
        'Ice Blue Red Top Zebra',
        'Iceland Gull',
        'Ichneumon Fly',
        'Icterine Warbler',
        'Iguana',
        'Ilsa Mocha Degu',
        'Impala',
        'Indian Cow',
        'Indian Glassfish',
        'Indian Ring-neck Parakeet',
        'Indigo Bunting',
        'Indian Hare',
        'Indian Palm Squirrel',
        'Indian Rhinoceros',
        'Indian Spiny Loach',
        'Indio-Chinese Tiger',
        'Inexpectatum Pleco',
        'Indigo-Winged Parrot',
        'Indian Skimmer',
        'Indri',
        'Intermediate Egret',
        'Invisible Rail',
        'Iranian Ground Jay',
        'Iridescent Shark',
        'Island Canary',
        'Island Whistler',
        'Ivory-backed Woodswallow',
        'Ivory Gull',
        'Izu Thrush',
    )
);