<?php defined('SYSPATH') or die('No direct script access.');

// Read more: http://wiki.answers.com/Q/What_are_some_adjectives_that_begin_with_the_letter_E#ixzz1et9La9m5
// Read more: http://wiki.answers.com/Q/What_animals_start_with_the_letter_e#ixzz1et9dehlQ

return array(
    'adjectives' => array(
        'jocosity',
        'judgmental',
        'jolliest',
        'jury-rigged',
        'judicial',
        'jumpy',
        'jovial',
        'jubilant',
        'joyous',
        'jealous',
        'juicy',
        'jumbled',
        'jaded',
        'jerky',
        'jingly',
        'jocund',
        'jittery',
        'junky',
        'joyful',
        'jagged',
        'jazzy',
        'jaunty',
        'jokey',
        'judicious',
        'judgemental',
        'jumbo',
        'just',
        'jejune',
        'jingoistic',
        'jammy',
        'jellied',
        'jumping',
        'jammed',
        'jitter',
        'jolly',
        'jinxed',
        'juvenile',
        'jocose',
        'juristic',
        'jury-rigged',
        'jiggly',
        'junk',
    ),
    'animals' => array(
        'Jabiru',
        'Jacana',
        'Jack Russell Terrier',
        'Jackal',
        'Jackdaw',
        'Jackel',
        'Jackrabbit',
        'Jack Russel Terrier',
        'Jagdterrier',
        'Jaguar',
        'Jämthund',
        'Japanese Akita',
        'Japanese beetle',
        'Japanese Chin',
        'Japanese fighting fish',
        'Japanese Spitz',
        'Japanese Terrier',
        'Jarabugo fish',
        'Jaxartosurus',
        'Jay',
        'Jaybird',
        'Jelen',
        'Jellyfish',
        'Jenny',
        'Jerboa',
        'Joey',
        'John dory',
        'Jumbo shrimp',
        'Jumping mouse',
        'Jumping spider',
        'Junco',
        'June bug',
    )
);