<?php defined('SYSPATH') or die('No direct script access.');

// Read more: http://wiki.answers.com/Q/What_are_some_adjectives_that_begin_with_the_letter_E#ixzz1et9La9m5
// Read more: http://wiki.answers.com/Q/What_animals_start_with_the_letter_e#ixzz1et9dehlQ

return array(
	'adjectives' => array(
		'Kaleidoscopic',
		'keelless',
		'keen',
		'Kelly Green',
		'kempt',
		'kept',
		'keratoid',
		'key',
		'keyed',
		'khaki',
		'kibbled',
		'Kicking',
		'kid',
		'kiddish',
		'killer',
		'kind',
		'kinesthetic',
		'kinetic',
		'Kindhearted',
		'kindly',
		'kindling',
		'kindred',
		'kingly',
		'king sized',
		'kinky',
		'kissable',
		'kitchen',
		'Kitschy',
		'kittenish',
		'Klutzy',
		'Kneaded',
		'knifelike',
		'knightly',
		'knitted',
		'knobbly',
		'knobby',
		'knockout',
		'knotted',
		'knotty',
		'knowing',
		'knowledgeable',
		'known',
		'kooky',
		'Korean',
		'kosher',
	),
	'animals' => array(
		'Kagu',
		'Kai Ken',
		'Kaka',
		'Kakapo',
		'Kakariki',
		'Kalumburu Kimberly Slider',
		'Kangaroo',
		'kangaroo mouse',
		'Kangaroo rat',
		'Karakul',
		'Karelian Bear Dog',
		'Katydid',
		'Kea',
		'Keel',
		'Keeshond',
		'Kelpfish',
		'Kentrosaurus',
		'Kermadec petrel',
		'Kerry Blue Terrier',
		'Kestrel',
		'Kid',
		'Killdeer',
		'Killer Whale',
		'Killifish',
		'Kimberley Mouse',
		'Kimberley rock',
		'Kimberley rock monitor',
		'Kingbird',
		'King cobra',
		'Kingfisher',
		'Kinglet',
		'King parrot',
		'King penguin',
		'King snake',
		'King\'s Hairstreak',
		'King\'s skink',
		'Kinkajou',
		'Kiskadee',
		'Kissing fish',
		'Kit Fox',
		'Kite',
		'Kitten',
		'Kittiwake',
		'Kitty',
		'Kiwi',
		'Knifejaw',
		'Koch\'s Sandgroper',
		'Knot eel',
		'Koala',
		'Kodiak bear',
		'Koi',
		'Komodo dragon',
		'Komondor',
		'Koodoo',
		'Kooikerhondje',
		'Koolie',
		'Korat',
		'Kookaburra',
		'Kowari',
		'Kouprey',
		'Krill',
		'Kromfohrländer',
		'Kronosaurus',
		'Kudu',
		'Kunming Wolfdog',
		'Kusimanse',
		'Kuvasz',
		'Kyi-Leo',
	)
);